### ISSUE TITLE
Как добавить передачу отрицательной температуры DHT22

### ISSUE THREAD

**Issue by selan61** [vkorobov/narodmon-Arduino-ENC28J60#1]
Виталий подскажите, как добавить передачу отрицательной температуры DHT22.
Проверил ваш скетч, немного переделал его под BMP280 и под другую библиотеку для DHT22.
А вот с отрицательной температурой не получается. По предварительным результатам работает лучше чем у Гладышева Дмитрия.

**Comment by vkorobov** [comment]
Там костыльный метод :) Всё руки не дойдут переделать на более свежие библиотеки. Функция itoa() - как раз и проверяет отрицательное ли число, если да, то  записывает сначала "-" в массив, а потом уже всё остальное.
```
void itoa(int n, char s[])
{
  int i, sign;

  if ((sign = n) < 0)       /* записываем знак */
    n = -n;                 /* делаем n положительным числом */
  i = 0;
  do {                      /* генерируем цифры в обратном порядке */
    s[i++] = n % 10 + '0';  /* берем следующую цифру */
  } while ((n /= 10) > 0);  /* удаляем */
  if (sign < 0)
    s[i++] = '-';
  s[i] = '\0';
  reverse(s);
}
```

**Comment by selan61** [comment]
Спасибо за ответ, сделал по аналогии с DS18B20. Вроде работает.
 Humidity = dht.readHumidity()*100;  // снимаем данные о влажности     
 strcat(replyBuffer, "&H22=");   // в буфер добавляем значок &H22=      
 ftoc(Humidity);  // в буфер добавляем значение влажности     

Temperature = dht.readTemperature()*100;  // снимаем данные о температуре      
strcat(replyBuffer, "&T22=");   // в буфер добавляем значок &T22=     
 if (Temperature < 0)       
 {        
  SignBit = 1; //если температура отрицательная, добавляем знак минуса     
     Temperature = -Temperature;   
     }       
 else      
  {      
    SignBit = 0;  
      }     
   if (SignBit)      
  {       
   strcat(replyBuffer, "-");  // в буфер добавляем знак минуса      
  }   
     ftoc(Temperature);  // в буфер добавляем значение температуры 
А как использовать функцию itoa() ? Неужели просто Так? 
Temperature = dht.readTemperature()*100;        
strcat(replyBuffer, "&T22="); 
 itoa(Temperature); 
И ещё подскажите, что делают в Вашем скетче функции len и uitoa? Или просто остались непричесанными от Дмитрия Гладышева?

**Comment by vkorobov** [comment]
itoa(int n, char s[]) преобразует число целое int n в символьный массив s[]. То есть ей передаётся число и массив куда нужно поместить символы 
char temp[17];
int Whole;
itoa(Whole, temp);

Для дробного числа типа float нужна аналогичная функция ftoc(int)

len() это из старого кода Дмитрия Гладышева, вычисление длины массива. В последней версии у меня этого уже нет
uitoa - это itoa только для типа unsigned int.
Эксперементировал :)
К слову, в последних версиях адруины есть отличные функции и класс String https://www.arduino.cc/en/Reference/StringObject
Где можно не заморачиваясь с кучей функций преобразовывать всё очень просто, примерно так:
 replyBuffer += String(lightMeter.readLightLevel());

**Comment by selan61** [comment]
Большое Вам спасибо, и за код и за консультации.

**Comment by vkorobov** [comment]
Пожалуйста! Успехов!
